"""init

Revision ID: 4000ffd775ee
Revises: 2bfe2db85dc4
Create Date: 2026-04-17 19:44:51.462443

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4000ffd775ee'
down_revision: Union[str, None] = '2bfe2db85dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
