from typing import Protocol
from uuid import UUID
from app.domain.entities.os import OrdemDeServico, StatusOS


class OSRepositoryPort(Protocol):
    """Interface que define as operações de persistência de Ordens de Serviço.

    As implementações concretas vivem em adapters/outbound/persistence.
    Os use cases dependem apenas desta interface, nunca da implementação.
    """

    def buscar_por_id(self, os_id: UUID) -> OrdemDeServico | None: ...
    def buscar_ou_falhar(self, os_id: UUID) -> OrdemDeServico: ...
    def buscar_para_escrita(self, os_id: UUID) -> OrdemDeServico: ...
    def listar(self, skip: int, limit: int, status: StatusOS | None) -> list[OrdemDeServico]: ...
    def buscar_por_cliente_id(self, cliente_id: UUID) -> list[OrdemDeServico]: ...
    def adicionar(self, entidade) -> None: ...
    def flush(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def refresh(self, entidade) -> None: ...
    def tempo_medio_execucao(self) -> dict: ...
